AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
    - arm64
    MemorySize: 128
    Timeout: 100
    LoggingConfig:
      LogFormat: JSON

Resources:
  wechatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/wechat.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SmartTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /wechat
            Method: POST
  SmartTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: smart
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
